name: Python Auto Test

on: [push]   # means: run this every time I push code to GitHub

jobs:
  test:      # name of the job
    runs-on: ubuntu-latest   # the environment (like a virtual computer)
    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # step 1: get your code from GitHub

      - name: Set up Python
        uses: actions/setup-python@v5   # step 2: install Python
        with:
          python-version: '3.10'        # version to use

      - name: Run a test command
        run: python --version           # step 3: run your Python command
